"""Contextual help for Phase D Thermal-Model Data."""

PHASE_D_HELP_ENTRIES = {
    "subpage.data_pipeline.phase_d_thermal_model_data": {
        "title": "Phase D: Thermal-Model Data",
        "summary": "Configure, execute, and inspect thermal-model-ready time-series datasets.",
        "details": "Phase D is a graphical frontend for the authoritative general Phase D campaign runner and a browser for the datasets that runner creates. It does not expose D2-D8 scientific implementation stages as separate workflows.",
    },
    "phase_d.page.campaign_builder": {
        "title": "Campaign Builder",
        "summary": "Save a reusable Phase D runner configuration.",
        "details": "Choose one completed Phase C run, narrow the exact runner-supported scope, and configure all scientific dataset-generation options. Generation and Aggregation ancestry are resolved from the selected Phase C lineage.",
    },
    "phase_d.page.execution": {
        "title": "Execution",
        "summary": "Execute a saved Phase D definition with the general runner.",
        "details": "Execution will reuse the exact command compiler owned by the Campaign Builder contract and add only run-time choices such as run ID, dry run, resume, overwrite, continue-on-error, and process control.",
    },
    "phase_d.page.results": {
        "title": "Results",
        "summary": "Inspect Phase D runner outputs and time-series datasets.",
        "details": "Results will filter the campaign dataset registry, load one selected manifest and Parquet dataset, and plot the actual available time-series columns rather than assuming identical signals across zones.",
    },
    "phase_d.section.identity": {"title": "Campaign", "summary": "Identity and notes for the reusable Phase D definition.", "details": "The campaign definition is separate from individual Phase D execution run IDs."},
    "phase_d.section.upstream": {"title": "Upstream Phase C Run", "summary": "Choose the completed Phase C run that anchors Phase D lineage.", "details": "Phase D obtains campaign root, matrix run, Generation ancestry, Aggregation rows, Phase C inference, and other required artifacts from this authoritative lineage."},
    "phase_d.section.scope": {"title": "Campaign Scope", "summary": "Filter successful Aggregation rows using only filters supported by the general runner.", "details": "Case ID, Aggregation ID, and Weight Mode compile directly to repeatable runner arguments. Strategy and Rule Set remain visible lineage context but are not invented as unsupported CLI filters."},
    "phase_d.section.representation": {"title": "Thermal-Model Data Representation", "summary": "Choose grouped or component heat-input representation.", "details": "Grouped representation uses Phase D ZIC/ZIR composition from scientifically available components. Component representation retains individual available heat-input components."},
    "phase_d.section.ml": {"title": "ML / SciML Dataset Policies", "summary": "Configure selected ML/SciML policies plus repeatable input lags and target horizons.", "details": "Policy-specific controls are shown only when their policy is selected. Input lags and target horizons are repeatable; the runner builds the Cartesian product of selected ML policies × lags × horizons."},
    "phase_d.section.ob": {"title": "Optimization / Bayesian Dataset Policies", "summary": "Configure only the selected identification/evaluation policies.", "details": "Seasonal Distributed uses within-season offset/train/test day windows; Seasonal Block Holdout uses whole meteorological seasons; Contiguous Identification uses one start datetime plus train/test durations; Custom Datetime Ranges is a separate policy for explicit repeatable ranges."},
    "phase_d.section.advanced": {"title": "Advanced Runner Options", "summary": "Configure normally stable backend runner options and campaign-level MLflow tracking.", "details": "Calendar year, output root, Parquet compression, and MLflow settings are part of the real runner contract. Defaults should normally be retained unless there is a deliberate reason to change them."},
    "phase_d.section.save": {"title": "Definition Preview & Save", "summary": "Validate the complete definition and inspect the exact runner command.", "details": "Preview and Save use the same typed PhaseDRunnerConfig and command compiler that Execution will use later."},
    "phase_d.input.campaign_id": {"title": "Phase D Campaign ID", "summary": "Stable ID of the reusable Phase D configuration.", "details": "This is not the timestamped Phase D execution run ID."},
    "phase_d.input.display_name": {"title": "Display Name", "summary": "Optional human-readable campaign name.", "details": "The stable Campaign ID remains authoritative."},
    "phase_d.input.machine_id": {"title": "Machine ID", "summary": "Machine profile associated with this saved definition.", "details": "The field is read-only in the normal Campaign Builder."},
    "phase_d.input.notes": {"title": "Notes", "summary": "Optional campaign notes.", "details": "Notes do not change scientific runner behavior."},
    "phase_d.input.phase_c_run": {"title": "Completed Phase C Campaign / Run", "summary": "Authoritative upstream Phase C execution consumed by Phase D.", "details": "Only completed or completed-with-warnings Phase C runs are offered. The selected run records the Aggregation matrix used by Phase C."},
    "phase_d.input.case_ids": {"title": "Generation Case(s)", "summary": "Repeatable --case-id filter for Phase D.", "details": "Empty means all successful matrix cases. Labels include building and weather while stored values preserve case_id."},
    "phase_d.input.aggregation_ids": {"title": "Aggregation ID(s)", "summary": "Repeatable --aggregation-id filter for Phase D.", "details": "Options are taken from successful Aggregation matrix rows. Labels may show strategy/rule context, but the stored runner value is the authoritative aggregation_id."},
    "phase_d.input.weight_modes": {"title": "Weight Mode(s)", "summary": "Repeatable --weight-mode filter for Phase D.", "details": "Empty means all weight modes represented by the selected Phase C matrix lineage."},
    "phase_d.input.max_aggregation_runs": {"title": "Maximum Aggregation Runs", "summary": "Optional runner limit after scope filtering.", "details": "This maps to --max-aggregation-runs and is primarily useful for controlled/smoke executions. Blank runs the full selected scope."},
    "phase_d.input.heat_representation": {"title": "Heat Representation", "summary": "Choose grouped ZIC/ZIR or individual heat components.", "details": "This maps directly to --heat-representation grouped|components."},
    "phase_d.input.qzivr_separate": {"title": "Visible-Lighting Radiant Gain", "summary": "Optionally keep QZivr_L separate from grouped ZIR.", "details": "This maps directly to --qzivr-separate. Leave unchecked for the normal grouped representation."},
    "phase_d.input.ml_policies": {"title": "ML / SciML Policies", "summary": "One or more supported ML/SciML partition policies.", "details": "Supported policies are monthly distributed holdout, chronological holdout, and seasonal holdout."},
    "phase_d.input.ml_input_lags": {"title": "ML Input Lag(s)", "summary": "One or more historical input-lag lengths in samples.", "details": "Enter comma-separated positive integers. Each becomes a repeatable --ml-input-lag argument."},
    "phase_d.input.ml_target_horizons": {"title": "ML Target Horizon(s)", "summary": "One or more future prediction horizons in samples.", "details": "Enter comma-separated positive integers such as 1,6,12. Each becomes a repeatable --ml-target-horizon argument; at 5-minute data these correspond to datasets containing targets through 5, 30, and 60 minutes respectively."},
    "phase_d.input.ml_fractions": {"title": "ML Fractions", "summary": "Train/test/validation fractions for Monthly Distributed and Chronological Holdout.", "details": "This shared runner parameter set is shown only when either fraction-based policy is selected. Each fraction must be strictly between 0 and 1 and the three values must sum to 1."},
    "phase_d.input.ml_sh_seasons": {"title": "ML Seasonal Holdout Seasons", "summary": "Assign disjoint meteorological seasons to train, test, and validation.", "details": "Winter, spring, summer, and fall assignments must be nonempty and mutually disjoint."},
    "phase_d.input.ob_policies": {"title": "Optimization / Bayesian Policies", "summary": "One or more supported Opt/Bayes selection policies.", "details": "Supported policies are seasonal distributed, seasonal block holdout, contiguous identification, and custom datetime ranges."},
    "phase_d.input.sd": {"title": "Seasonal Distributed", "summary": "Configure one train/test window inside every meteorological season.", "details": "For each winter/spring/summer/fall season, Phase D skips Season Offset Days, takes Train Days, then immediately takes Test Days. The sum must fit the shortest 90-day season. There are no arbitrary start/end dates for this policy."},
    "phase_d.input.sbh": {"title": "Seasonal Block Holdout", "summary": "Assign whole meteorological seasons to train and test.", "details": "This policy has no arbitrary date-range input. Choose disjoint winter/spring/summer/fall groups; unselected seasons remain excluded."},
    "phase_d.input.ci": {"title": "Contiguous Identification", "summary": "Choose one start datetime, then contiguous train and test durations.", "details": "Start Datetime format should be ISO-like YYYY-MM-DDTHH:MM:SS, e.g. 2001-01-01T00:05:00. Blank uses the first canonical timestamp. Train ends after Train Days; Test begins immediately and ends after Test Days. The start must lie on the canonical timestamp axis."},
    "phase_d.input.cdr": {"title": "Custom Datetime Ranges", "summary": "Separate policy for one or more explicit half-open train/test ranges.", "details": "Enter one range per line as YYYY-MM-DDTHH:MM:SS/YYYY-MM-DDTHH:MM:SS, for example 2001-01-01T00:05:00/2001-01-08T00:05:00. START is included and END is excluded. Train/test ranges cannot overlap, range starts must lie on the canonical timestamp axis, and at least one train plus one test range are required."},
    "phase_d.input.calendar_year": {"title": "Phase D Calendar Year", "summary": "Canonical non-leap calendar year used by Phase D alignment/output.", "details": "The current general runner default is 2001."},
    "phase_d.input.parquet_compression": {"title": "Parquet Compression", "summary": "Compression codec passed to final Phase D Parquet writing.", "details": "The current runner default is zstd."},
    "phase_d.input.output_root": {"title": "Output Root", "summary": "Root beneath which the runner writes the phase_d output hierarchy.", "details": "Blank uses the selected campaign root, matching the general runner default."},
    "phase_d.input.mlflow": {"title": "MLflow", "summary": "Optional campaign-level Phase D MLflow settings.", "details": "Phase D logs compact campaign parameters, metrics, and registry/manifest artifacts rather than bulk time-series Parquet data."},

    "phase_d.execution.saved_definition": {
        "title": "Saved Phase D Campaign",
        "summary": "Choose the reusable Campaign Builder definition to execute.",
        "details": "The selected definition owns all Phase D scientific options, parent Phase C lineage, scope filters, temporal policies, heat representation, output settings, and MLflow settings. Execution does not redefine those choices.",
    },
    "phase_d.execution.request": {
        "title": "Execution Request",
        "summary": "Add only run-time controls to the saved Phase D definition.",
        "details": "Run ID, Dry Run, Resume, Overwrite Existing, and Continue on Error are the only normal Tab-2 controls because they belong to the authoritative general runner's execution interface rather than to the scientific campaign definition.",
    },
    "phase_d.execution.run_id": {
        "title": "Phase D Run ID",
        "summary": "Unique identifier for this campaign execution.",
        "details": "A timestamped value such as phase_d_20260827_103200 is suggested automatically. Use a new Run ID for a fresh execution. Reusing an existing campaign Run ID can rewrite its compact campaign-level plan/registry files.",
    },
    "phase_d.execution.dry_run": {
        "title": "Dry Run",
        "summary": "Plan the selected Phase D execution without building per-aggregation datasets.",
        "details": "Dry Run passes --dry-run to the authoritative Phase D runner. The runner records campaign planning/summary artifacts but skips per-aggregation dataset construction.",
    },
    "phase_d.execution.resume": {
        "title": "Resume",
        "summary": "Reuse compatible completed Phase D aggregation outputs where the scientific runner permits it.",
        "details": "Resume maps directly to --resume. For selected aggregation outputs that already exist, the authoritative runner verifies completion/configuration compatibility, skips compatible completed outputs, and rebuilds incomplete/incompatible outputs. Resume and Overwrite Existing are mutually exclusive.",
    },
    "phase_d.execution.overwrite": {
        "title": "Overwrite Existing",
        "summary": "Deliberately rebuild selected Phase D aggregation outputs that already exist.",
        "details": "Overwrite Existing maps directly to --overwrite-existing. The authoritative runner removes an existing selected aggregation output directory before rebuilding it. This is destructive for those selected Phase D outputs and requires confirmation. It is mutually exclusive with Resume.",
    },
    "phase_d.execution.continue_on_error": {
        "title": "Continue on Error",
        "summary": "Continue to later aggregation runs after an individual aggregation failure.",
        "details": "This maps directly to --continue-on-error. Without it, the campaign runner stops after the first failed aggregation run. Failures remain recorded in the campaign registries either way.",
    },
    "phase_d.execution.progress": {
        "title": "Aggregation Progress",
        "summary": "Track completed/skipped/failed aggregation runs and dataset registration.",
        "details": "The Dash execution service reads the compact campaign plan, aggregation_run_registry.csv, dataset_registry.csv, failures.csv, and current per-aggregation log that the authoritative runner already creates. It does not duplicate scientific progress logic.",
    },
    "phase_d.execution.console": {
        "title": "Live Console",
        "summary": "View top-level runner output plus the active aggregation log tail.",
        "details": "The general Phase D runner writes each aggregation's detailed stdout/stderr to a campaign log file. The Dash console combines top-level process output with a bounded tail of the latest aggregation log so long-running dataset construction remains observable without retaining full logs in memory.",
    },
    "phase_d.execution.stop": {
        "title": "Stop Phase D",
        "summary": "Terminate the active Phase D runner subprocess tree.",
        "details": "Stop terminates the top-level Phase D runner and its current child aggregation process. Artifacts already written remain on disk; Stop does not roll back scientific outputs.",
    },

    "phase_d.results.run": {"title": "Phase D Run", "summary": "Choose one Phase D campaign execution.", "details": "Results discovers compact phase_d_campaign_run_manifest.json files. The selected run owns the dataset registry used by every downstream Results filter."},
    "phase_d.results.filters": {"title": "Dataset Filters", "summary": "Filter only the compact Phase D dataset registry.", "details": "Building, weather, case, aggregation lineage, silo, relationship, zone, heat representation, policy, lag, and horizon come directly from dataset_registry.csv. The filters never reconstruct Phase D science."},
    "phase_d.results.dataset": {"title": "Selected Final Dataset", "summary": "Choose exactly one final Phase D realization.", "details": "Each option corresponds to one registry row and one authoritative data.parquet + manifest.json pair."},
    "phase_d.results.dataset_summary": {"title": "Dataset Summary", "summary": "Read the selected dataset's scientific manifest.", "details": "The summary reports exact lineage, silo/relationship, temporal policy, annual/included/excluded counts, coverage, and final-column count."},
    "phase_d.results.timeseries": {"title": "Thermal-Model Time Series", "summary": "Plot actual final thermal-model columns.", "details": "Signal names, physical roles, temporal roles, units, zones, and offsets are read from manifest.final_columns. No assumption is made that every zone has identical signals."},
    "phase_d.results.signals": {"title": "Signals", "summary": "Select final model-input or prediction-target columns.", "details": "Labels distinguish zone, base physical signal, lag/target role, and units. Lag 0 represents the anchor-time model input; negative offsets are historical lags; target columns are future zone-temperature targets."},
    "phase_d.results.partition": {"title": "Partition", "summary": "Filter the selected final dataset by its recorded partition.", "details": "Included Rows uses the dataset's boolean included field. ML/SciML commonly exposes train/validation/test/excluded; Optimization/Bayesian policies expose the partitions recorded in the selected manifest."},
    "phase_d.results.max_points": {"title": "Maximum Plotted Rows", "summary": "Bound browser plot size without changing the scientific dataset.", "details": "When selected rows exceed the limit, Results uses deterministic stride sampling for display. Visible-plot downloads reproduce exactly that displayed sampling. The separate selected-dataset ZIP always contains the full authoritative Parquet."},
    "phase_d.results.preview": {"title": "Dataset Preview", "summary": "Inspect the first rows and exact final columns.", "details": "The preview reads only the first bounded Arrow batch from the selected data.parquet after a single dataset has been chosen; it does not load the full annual Parquet merely to show the preview."},

}
