"""Central registry for major pages and horizontal subpage tabs."""

MAJOR_PAGES = [{'id': 'home', 'label': 'Home', 'icon': 'bi-house-door', 'path': '/'},
 {'id': 'campaigns', 'label': 'Campaigns', 'icon': 'bi-grid-3x3-gap', 'path': '/campaigns'},
 {'id': 'data_pipeline',
  'label': 'Data Pipeline',
  'icon': 'bi-diagram-3',
  'path': '/data-pipeline'},
 {'id': 'thermal_modeling',
  'label': 'Thermal Modeling',
  'icon': 'bi-cpu',
  'path': '/thermal-modeling'},
 {'id': 'model_catalog',
  'label': 'Model Catalog',
  'icon': 'bi-collection',
  'path': '/model-catalog'},
 {'id': 'simulators', 'label': 'Simulators', 'icon': 'bi-play-btn', 'path': '/simulators'},
 {'id': 'results_explorer',
  'label': 'Results Explorer',
  'icon': 'bi-graph-up',
  'path': '/results-explorer'},
 {'id': 'publication_studio',
  'label': 'Publication Studio',
  'icon': 'bi-file-earmark-bar-graph',
  'path': '/publication-studio'},
 {'id': 'settings', 'label': 'Settings', 'icon': 'bi-gear', 'path': '/settings'}]

SUBPAGES = {'home': [{'id': 'overview', 'label': 'Overview', 'icon': 'bi-speedometer2'},
          {'id': 'recent_activity', 'label': 'Recent Activity', 'icon': 'bi-clock-history'},
          {'id': 'system_status', 'label': 'System Status', 'icon': 'bi-activity'},
          {'id': 'quick_actions', 'label': 'Quick Actions', 'icon': 'bi-lightning-charge'}],
 'campaigns': [{'id': 'browser', 'label': 'Campaign Browser', 'icon': 'bi-search'},
               {'id': 'builder', 'label': 'Campaign Builder', 'icon': 'bi-tools'},
               {'id': 'matrix_preview', 'label': 'Matrix Preview', 'icon': 'bi-table'},
               {'id': 'monitor', 'label': 'Campaign Monitor', 'icon': 'bi-display'},
               {'id': 'templates', 'label': 'Campaign Templates', 'icon': 'bi-files'}],
 'data_pipeline': [{'id': 'phase_a_generation',
                    'label': 'Phase A: Generation',
                    'icon': 'bi-building-gear'},
                   {'id': 'phase_b_aggregation',
                    'label': 'Phase B: Aggregation',
                    'icon': 'bi-bounding-box-circles'},
                   {'id': 'phase_c_heat_input',
                    'label': 'Phase C: Heat-Input Regression',
                    'icon': 'bi-thermometer-sun'},
                   {'id': 'phase_d_thermal_model_data',
                    'label': 'Phase D: Thermal-Model Data',
                    'icon': 'bi-database-gear'}],
 'thermal_modeling': [{'id': 'datasets', 'label': 'Thermal-Model Datasets', 'icon': 'bi-database'},
                      {'id': 'ann_sequence_models',
                       'label': 'ANN / Sequence Models',
                       'icon': 'bi-diagram-2'},
                      {'id': 'scientific_ml',
                       'label': 'Scientific Machine Learning',
                       'icon': 'bi-bezier'},
                      {'id': 'optimization',
                       'label': 'Optimization-Based Modeling',
                       'icon': 'bi-sliders'},
                      {'id': 'bayesian_inference',
                       'label': 'Bayesian Inference',
                       'icon': 'bi-distribute-vertical'},
                      {'id': 'run_monitor',
                       'label': 'Run Monitor',
                       'icon': 'bi-pc-display-horizontal'}],
 'model_catalog': [{'id': 'browse', 'label': 'Browse Models', 'icon': 'bi-search'},
                   {'id': 'model_details', 'label': 'Model Details', 'icon': 'bi-card-list'},
                   {'id': 'portability',
                    'label': 'Model Portability',
                    'icon': 'bi-box-arrow-in-right'},
                   {'id': 'validation', 'label': 'Model Validation', 'icon': 'bi-check2-square'},
                   {'id': 'comparison_tray', 'label': 'Comparison Tray', 'icon': 'bi-columns-gap'}],
 'simulators': [{'id': 'smartcommunitysim',
                 'label': 'Smart Community Simulator',
                 'icon': 'bi-houses'},
                {'id': 'smartbuildingssim',
                 'label': 'Smart Buildings Simulator',
                 'icon': 'bi-buildings'},
                {'id': 'opendsssim', 'label': 'OpenDSS Simulator', 'icon': 'bi-diagram-3-fill'},
                {'id': 'co_simulationsim',
                 'label': 'Co-Simulation Platform',
                 'icon': 'bi-intersect'}],
 'results_explorer': [{'id': 'single_experiment',
                       'label': 'Single Experiment',
                       'icon': 'bi-file-earmark-text'},
                      {'id': 'cross_experiment',
                       'label': 'Cross-Experiment Comparison',
                       'icon': 'bi-layout-three-columns'},
                      {'id': 'time_series',
                       'label': 'Time-Series Explorer',
                       'icon': 'bi-graph-up-arrow'},
                      {'id': 'metrics', 'label': 'Metrics Explorer', 'icon': 'bi-bar-chart'},
                      {'id': 'parameters', 'label': 'Parameter Explorer', 'icon': 'bi-toggles'},
                      {'id': 'diagnostics',
                       'label': 'Diagnostics Explorer',
                       'icon': 'bi-clipboard2-pulse'},
                      {'id': 'simulator_results',
                       'label': 'Simulator Results',
                       'icon': 'bi-play-circle'}],
 'publication_studio': [{'id': 'figure_builder', 'label': 'Figure Builder', 'icon': 'bi-image'},
                        {'id': 'table_builder', 'label': 'Table Builder', 'icon': 'bi-table'},
                        {'id': 'saved_specifications',
                         'label': 'Saved Specifications',
                         'icon': 'bi-bookmark-check'},
                        {'id': 'export_history',
                         'label': 'Export History',
                         'icon': 'bi-clock-history'}],
 'settings': [{'id': 'paths', 'label': 'Paths', 'icon': 'bi-folder2-open'},
              {'id': 'machines', 'label': 'Machines', 'icon': 'bi-pc-display'},
              {'id': 'environments', 'label': 'Environments', 'icon': 'bi-box'},
              {'id': 'mlflow', 'label': 'MLflow', 'icon': 'bi-signpost-split'},
              {'id': 'visualization', 'label': 'Visualization', 'icon': 'bi-palette'},
              {'id': 'help', 'label': 'Help and About', 'icon': 'bi-question-circle'}]}

PAGE_BY_PATH = {page["path"]: page for page in MAJOR_PAGES}
PAGE_BY_ID = {page["id"]: page for page in MAJOR_PAGES}
