"""Dash-facing services for Phase B Aggregation."""

from .definition_store import (
    definition_path,
    definition_root,
    list_definitions,
    load_definition,
    save_definition,
)
from .upstream_generation import (
    campaigns_root,
    discover_generation_cases,
    discover_parent_campaigns,
    filter_generation_cases,
    parent_campaign_options,
    selection_facets,
)
from .builder import (
    build_definition,
    build_plan_requests,
    custom_grouping_path,
    relative_custom_grouping_path,
    save_builder_definition,
    save_custom_grouping,
    validate_custom_group_rows,
)
from .results_data import (
    build_selected_data_export as build_selected_aggregation_data_export,
    campaign_options as result_campaign_options,
    compact_case_run_rows,
    compact_missing_rows,
    discover_matrix_runs,
    discover_zones as discover_result_zones,
    filter_result_index,
    load_matrix_result,
    load_selected_signals,
    matrix_run_options,
    result_index,
    result_options,
    run_options as result_run_options,
    variable_catalog as result_variable_catalog,
    variable_column_options as result_variable_column_options,
    variable_options as result_variable_options,
)
from .execution import (
    AggregationProcessManager,
    MANAGER,
    command_for,
    command_text,
    definition_summary,
    runner_script,
)

__all__ = [
    "definition_path",
    "definition_root",
    "list_definitions",
    "load_definition",
    "save_definition",
    "campaigns_root",
    "discover_generation_cases",
    "discover_parent_campaigns",
    "filter_generation_cases",
    "parent_campaign_options",
    "selection_facets",
    "build_definition",
    "build_plan_requests",
    "custom_grouping_path",
    "relative_custom_grouping_path",
    "save_builder_definition",
    "save_custom_grouping",
    "validate_custom_group_rows",
    "AggregationProcessManager",
    "MANAGER",
    "command_for",
    "command_text",
    "definition_summary",
    "runner_script",
    "result_campaign_options",
    "compact_case_run_rows",
    "compact_missing_rows",
    "discover_matrix_runs",
    "load_matrix_result",
    "matrix_run_options",
    "build_selected_aggregation_data_export",
    "discover_result_zones",
    "filter_result_index",
    "load_selected_signals",
    "result_index",
    "result_options",
    "result_run_options",
    "result_variable_catalog",
    "result_variable_column_options",
    "result_variable_options",
]
